---
services:
  semaphore:
    image: semaphoreui/semaphore:v2.15.0
    container_name: semaphore
    ports:
      - "3001:3000"
    environment:
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ADMIN_PASSWORD: "YourStrongPasswordHere"
      SEMAPHORE_DB_DIALECT: bolt
    restart: unless-stopped
...
